// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-p2txnJt-2GPvF547GDuSYLQIcNx4do',
    appId: '1:167571190019:web:46ec0fc8acd55e81033936',
    messagingSenderId: '167571190019',
    projectId: 'leelacasting-b610f',
    authDomain: 'leelacasting-b610f.firebaseapp.com',
    storageBucket: 'leelacasting-b610f.appspot.com',
    measurementId: 'G-8QKQBH5WG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1JSE__wA4XMr-0lfyvDrUU3QkrPxz5vk',
    appId: '1:167571190019:android:0bd0e7605593f081033936',
    messagingSenderId: '167571190019',
    projectId: 'leelacasting-b610f',
    storageBucket: 'leelacasting-b610f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkjYWbgaIETn-FN4-n5Bww7RtbgnTTfww',
    appId: '1:167571190019:ios:c515a5588ca673a6033936',
    messagingSenderId: '167571190019',
    projectId: 'leelacasting-b610f',
    storageBucket: 'leelacasting-b610f.appspot.com',
    iosBundleId: 'com.thvfuturistai.leelacasting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkjYWbgaIETn-FN4-n5Bww7RtbgnTTfww',
    appId: '1:167571190019:ios:c515a5588ca673a6033936',
    messagingSenderId: '167571190019',
    projectId: 'leelacasting-b610f',
    storageBucket: 'leelacasting-b610f.appspot.com',
    iosBundleId: 'com.thvfuturistai.leelacasting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL-p2txnJt-2GPvF547GDuSYLQIcNx4do',
    appId: '1:167571190019:web:b96e85a6cb4ffc92033936',
    messagingSenderId: '167571190019',
    projectId: 'leelacasting-b610f',
    authDomain: 'leelacasting-b610f.firebaseapp.com',
    storageBucket: 'leelacasting-b610f.appspot.com',
    measurementId: 'G-KF6XV0SKGE',
  );
}
